/*
  The free psychology audit: a stranger's answers, with no account.

  This is the only table in the app written by people who are not signed in,
  and the shape is copied from waitlist rather than invented - one INSERT
  policy and NO SELECT POLICY AT ALL. That is deliberate and it is the
  correction that table needed: its original policy was USING (true), which
  let anybody read every email that had ever been collected. A table the
  public writes to must not be a table the public can read.

  Everything here is therefore write-only from a browser. Reading it is a
  service-role job - reports, exports, and whatever nurture sequence
  eventually sends these people their breakdown.

  Anonymous on purpose. The traffic is cold, from Instagram, and the
  research is blunt about it: gating a quiz behind a signup "defeats the
  entire purpose", and even an email gate on the RESULT loses 30-50% of the
  people who finished. So the audit asks for nothing until it has already
  given something.
*/

CREATE TABLE IF NOT EXISTS public.psychology_audits (
  /*
    Generated by the browser, not the database.

    The row is written when somebody finishes the questions, and the email -
    if they leave one - arrives afterwards as an update to that same row.
    With no SELECT policy the client cannot read back an id it did not
    already know, so it brings its own.
  */
  id uuid PRIMARY KEY,
  archetype text NOT NULL,
  /* The raw answers, for working out later which questions actually
     discriminate between archetypes and which are dead weight. */
  answers jsonb NOT NULL DEFAULT '{}'::jsonb,
  email text,
  /* Where they came from, so an Instagram campaign can be told apart from
     organic traffic without a third-party analytics round trip. */
  source text,
  created_at timestamptz NOT NULL DEFAULT now(),
  email_added_at timestamptz
);

CREATE INDEX IF NOT EXISTS psychology_audits_created_idx
  ON public.psychology_audits (created_at DESC);
CREATE INDEX IF NOT EXISTS psychology_audits_archetype_idx
  ON public.psychology_audits (archetype);
/* Partial: the only rows worth scanning by email are the ones that have one. */
CREATE INDEX IF NOT EXISTS psychology_audits_email_idx
  ON public.psychology_audits (lower(email)) WHERE email IS NOT NULL;

ALTER TABLE public.psychology_audits ENABLE ROW LEVEL SECURITY;

/*
  Anybody may record an audit. Nothing may read one.

  The check pins archetype to the known set, so the column cannot be used as
  free text storage by anyone who finds the endpoint, and insists the email
  is absent at this point - it arrives through the update below or not at
  all.
*/
CREATE POLICY "Anyone can record an audit"
  ON public.psychology_audits
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (
    archetype IN ('revenge', 'hesitator', 'rule_breaker', 'giver_backer', 'overtrader')
    AND email IS NULL
    AND length(coalesce(source, '')) <= 64
  );

/*
  Attaching an email to an audit, without making audits readable.

  The obvious implementation is an UPDATE policy with USING (email IS NULL),
  and it silently does nothing: an UPDATE ... WHERE id = x has to FIND the
  row before it can change it, and finding rows is governed by the SELECT
  policy. This table deliberately has none, so no rows match, zero are
  updated, and PostgREST reports success. The screen says "Sent. Check your
  inbox" over an email that was never saved.

  Adding a SELECT policy would fix it and reopen precisely the hole this
  table exists to avoid. So the write happens inside a function that runs as
  its owner instead - the same shape as has_active_subscription and the
  synced-account limits elsewhere in this schema.

  The function is the only way in. It validates the address itself rather
  than trusting a policy check, and it is set-once: the WHERE insists the
  row has no email yet, so knowing an id cannot overwrite somebody else's.
*/

CREATE OR REPLACE FUNCTION public.attach_audit_email(p_audit_id uuid, p_email text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_email text := lower(trim(coalesce(p_email, '')));
BEGIN
  IF v_email = ''
     OR v_email !~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
     OR length(v_email) > 255 THEN
    RETURN false;
  END IF;

  UPDATE public.psychology_audits
  SET email = v_email, email_added_at = now()
  WHERE id = p_audit_id AND email IS NULL;

  RETURN FOUND;
END;
$$;

REVOKE ALL ON FUNCTION public.attach_audit_email(uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.attach_audit_email(uuid, text) TO anon, authenticated;

/*
  Send the breakdown the audit page promised.

  The result page says "we'll email you the full breakdown" in exchange for
  an address. Collecting the address and sending nothing is a promise broken
  to exactly the people the audit exists to win over.

  Fired by a trigger rather than by the browser, for the same reason the
  welcome email is: a tab closed a second after submitting should not be the
  difference between getting the thing and not. It also means the client
  cannot ask us to mail an address it invented - the trigger only fires on a
  row the set-once function has already written.
*/

ALTER TABLE public.psychology_audits
  ADD COLUMN IF NOT EXISTS email_sent_at timestamptz;

COMMENT ON COLUMN public.psychology_audits.email_sent_at IS
  'When the breakdown was dispatched. An email with an address but no sent stamp is one that failed to go out, which is worth being able to find.';

/*
  The unsubscribe token.

  One per row rather than one per address, matching abandon_signup_emails:
  the token is the proof in the link, it grants nothing except the ability
  to stop receiving mail, and a token tied to a single send cannot be used
  to enumerate anything. Somebody who takes the audit twice gets two
  tokens, and either one suppresses the address.
*/
ALTER TABLE public.psychology_audits
  ADD COLUMN IF NOT EXISTS unsubscribe_token uuid NOT NULL DEFAULT gen_random_uuid();

CREATE UNIQUE INDEX IF NOT EXISTS psychology_audits_unsub_token_idx
  ON public.psychology_audits (unsubscribe_token);

CREATE OR REPLACE FUNCTION public.notify_audit_email()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_secret text;
BEGIN
  /*
    cron_secret, shared with the other database-triggered functions rather
    than a secret of its own. A webhook secret that exists everywhere except
    production fails closed and silently - 403, no email, nothing said - and
    the claim being made here is "this call came from our own database",
    which is the same claim those functions already check.
  */
  SELECT value INTO v_secret FROM internal_config WHERE key = 'cron_secret';
  IF v_secret IS NULL THEN
    RAISE WARNING 'cron_secret missing - audit breakdown not sent for %', NEW.id;
    RETURN NEW;
  END IF;

  PERFORM net.http_post(
    url := 'https://irtlwmpcfzjrlrxicxbk.supabase.co/functions/v1/send-audit-email',
    body := jsonb_build_object('auditId', NEW.id),
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'X-Webhook-Secret', v_secret
    )
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_audit_email ON public.psychology_audits;

/*
  Only when an address actually arrives.

  UPDATE OF email with the WHEN clause means this fires once, on the
  transition from no email to an email - not on the insert, which has none,
  and not again if anything else on the row is ever touched.
*/
CREATE TRIGGER trg_notify_audit_email
  AFTER UPDATE OF email ON public.psychology_audits
  FOR EACH ROW
  WHEN (OLD.email IS NULL AND NEW.email IS NOT NULL)
  EXECUTE FUNCTION public.notify_audit_email();
