/*
  The free psychology audit: a stranger's answers, with no account.

  This is the only table in the app written by people who are not signed in,
  and the shape is copied from waitlist rather than invented - one INSERT
  policy and NO SELECT POLICY AT ALL. That is deliberate and it is the
  correction that table needed: its original policy was USING (true), which
  let anybody read every email that had ever been collected. A table the
  public writes to must not be a table the public can read.

  Everything here is therefore write-only from a browser. Reading it is a
  service-role job - reports, exports, and whatever nurture sequence
  eventually sends these people their breakdown.

  Anonymous on purpose. The traffic is cold, from Instagram, and the
  research is blunt about it: gating a quiz behind a signup "defeats the
  entire purpose", and even an email gate on the RESULT loses 30-50% of the
  people who finished. So the audit asks for nothing until it has already
  given something.
*/

CREATE TABLE IF NOT EXISTS public.psychology_audits (
  /*
    Generated by the browser, not the database.

    The row is written when somebody finishes the questions, and the email -
    if they leave one - arrives afterwards as an update to that same row.
    With no SELECT policy the client cannot read back an id it did not
    already know, so it brings its own.
  */
  id uuid PRIMARY KEY,
  archetype text NOT NULL,
  /* The raw answers, for working out later which questions actually
     discriminate between archetypes and which are dead weight. */
  answers jsonb NOT NULL DEFAULT '{}'::jsonb,
  email text,
  /* Where they came from, so an Instagram campaign can be told apart from
     organic traffic without a third-party analytics round trip. */
  source text,
  created_at timestamptz NOT NULL DEFAULT now(),
  email_added_at timestamptz
);

CREATE INDEX IF NOT EXISTS psychology_audits_created_idx
  ON public.psychology_audits (created_at DESC);
CREATE INDEX IF NOT EXISTS psychology_audits_archetype_idx
  ON public.psychology_audits (archetype);
/* Partial: the only rows worth scanning by email are the ones that have one. */
CREATE INDEX IF NOT EXISTS psychology_audits_email_idx
  ON public.psychology_audits (lower(email)) WHERE email IS NOT NULL;

ALTER TABLE public.psychology_audits ENABLE ROW LEVEL SECURITY;

/*
  Anybody may record an audit. Nothing may read one.

  The check pins archetype to the known set, so the column cannot be used as
  free text storage by anyone who finds the endpoint, and insists the email
  is absent at this point - it arrives through the update below or not at
  all.
*/
CREATE POLICY "Anyone can record an audit"
  ON public.psychology_audits
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (
    archetype IN ('revenge', 'hesitator', 'rule_breaker', 'giver_backer', 'overtrader')
    AND email IS NULL
    AND length(coalesce(source, '')) <= 64
  );

/*
  Attaching an email to an audit, without making audits readable.

  The obvious implementation is an UPDATE policy with USING (email IS NULL),
  and it silently does nothing: an UPDATE ... WHERE id = x has to FIND the
  row before it can change it, and finding rows is governed by the SELECT
  policy. This table deliberately has none, so no rows match, zero are
  updated, and PostgREST reports success. The screen says "Sent. Check your
  inbox" over an email that was never saved.

  Adding a SELECT policy would fix it and reopen precisely the hole this
  table exists to avoid. So the write happens inside a function that runs as
  its owner instead - the same shape as has_active_subscription and the
  synced-account limits elsewhere in this schema.

  The function is the only way in. It validates the address itself rather
  than trusting a policy check, and it is set-once: the WHERE insists the
  row has no email yet, so knowing an id cannot overwrite somebody else's.
*/

CREATE OR REPLACE FUNCTION public.attach_audit_email(p_audit_id uuid, p_email text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_email text := lower(trim(coalesce(p_email, '')));
BEGIN
  IF v_email = ''
     OR v_email !~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
     OR length(v_email) > 255 THEN
    RETURN false;
  END IF;

  UPDATE public.psychology_audits
  SET email = v_email, email_added_at = now()
  WHERE id = p_audit_id AND email IS NULL;

  RETURN FOUND;
END;
$$;

REVOKE ALL ON FUNCTION public.attach_audit_email(uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.attach_audit_email(uuid, text) TO anon, authenticated;
